# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "784be008b7681b6d7a569f01bcb4578d"
name = "scandishop"
handle = "scandishop"
application_url = "https://nickel-establishing-complications-funky.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "john-onyango-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nickel-establishing-complications-funky.trycloudflare.com/auth/callback",
  "https://nickel-establishing-complications-funky.trycloudflare.com/auth/shopify/callback",
  "https://nickel-establishing-complications-funky.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
